create table if not exists public.produtos (
  id text primary key,
  nome text not null,
  marca text not null,
  preco numeric(10,2) not null,
  imagem_url text not null,
  descricao text not null,
  categoria text not null,
  criado_em timestamptz not null default now()
);

create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  paypal_order_id text not null unique,
  status text not null,
  valor_total numeric(10,2) not null,
  moeda text not null default 'BRL',
  email_cliente text,
  criado_em timestamptz not null default now()
);

create table if not exists public.pedido_itens (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references public.pedidos(id) on delete cascade,
  produto_id text references public.produtos(id),
  nome_produto text not null,
  marca_produto text,
  categoria_produto text,
  descricao_produto text,
  imagem_produto text,
  quantidade integer not null check (quantidade > 0),
  valor_unitario numeric(10,2) not null,
  valor_total_item numeric(10,2) not null,
  criado_em timestamptz not null default now()
);

create index if not exists idx_pedidos_paypal_order_id on public.pedidos(paypal_order_id);
create index if not exists idx_pedido_itens_pedido_id on public.pedido_itens(pedido_id);
create index if not exists idx_pedido_itens_produto_id on public.pedido_itens(produto_id);

alter table public.produtos enable row level security;
alter table public.pedidos enable row level security;
alter table public.pedido_itens enable row level security;

drop policy if exists "service role gerencia produtos" on public.produtos;
create policy "service role gerencia produtos"
on public.produtos
as permissive
for all
to service_role
using (true)
with check (true);

drop policy if exists "service role gerencia pedidos" on public.pedidos;
create policy "service role gerencia pedidos"
on public.pedidos
as permissive
for all
to service_role
using (true)
with check (true);

drop policy if exists "service role gerencia pedido_itens" on public.pedido_itens;
create policy "service role gerencia pedido_itens"
on public.pedido_itens
as permissive
for all
to service_role
using (true)
with check (true);

insert into public.produtos (id, nome, marca, preco, imagem_url, descricao, categoria)
values
  ('1', 'Ácido Glicólico Botik Gelée Limpeza Facial', 'O BOTICÁRIO', 129.00, 'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=800&auto=format&fit=crop', 'Geléia concentrada de limpeza facial com ácido glicólico que renova e ilumina a pele.', 'Limpeza'),
  ('2', 'Kit Botik Nutritivo Resveratrol', 'O BOTICÁRIO', 149.90, 'https://images.unsplash.com/photo-1612817288484-6f916006741a?q=80&w=800&auto=format&fit=crop', 'Creme nutritivo firmador com resveratrol e silício para uma pele mais firme e radiante.', 'Tratamento'),
  ('3', 'Creme Hidratante Botik Vitamina C', 'O BOTICÁRIO', 99.90, 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=800&auto=format&fit=crop', 'Creme hidratante antioxidante com Vitamina C que protege contra radicais livres.', 'Hidratação'),
  ('4', 'Água Micelar Cica Pantenol e Ceramidas', 'O BOTICÁRIO', 75.66, 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=800&auto=format&fit=crop', 'Remove impurezas e repara a barreira da pele com pantenol e ceramidas.', 'Limpeza'),
  ('5', 'Sérum de Alta Potência Vitamina C 10%', 'O BOTICÁRIO', 229.90, 'https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=800&auto=format&fit=crop', 'Sérum concentrado com 10% de Vitamina C pura para iluminação intensa.', 'Tratamento'),
  ('6', 'Gel de Limpeza Facial Cica Pantenol e Ceramidas', 'O BOTICÁRIO', 78.90, 'https://images.unsplash.com/photo-1556228515-919532d0c2e9?q=80&w=800&auto=format&fit=crop', 'Limpeza suave e hipoalergênica que acalma e repara a pele.', 'Limpeza'),
  ('7', 'Gel de Limpeza Facial Ácido Mandélico + Salicílico', 'O BOTICÁRIO', 106.90, 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?q=80&w=800&auto=format&fit=crop', 'Ideal para peles oleosas, ajuda a controlar a oleosidade e reduzir poros.', 'Limpeza'),
  ('8', 'Sérum Facial Retinol Puro 0.3%', 'O BOTICÁRIO', 332.90, 'https://images.unsplash.com/photo-1617897903246-719242758050?q=80&w=800&auto=format&fit=crop', 'Tratamento anti-idade potente que reduz rugas e uniformiza a textura da pele.', 'Tratamento')
on conflict (id) do update
set
  nome = excluded.nome,
  marca = excluded.marca,
  preco = excluded.preco,
  imagem_url = excluded.imagem_url,
  descricao = excluded.descricao,
  categoria = excluded.categoria;
